### PR TITLE
Permutils

### PR DESCRIPTION
**Pull request by alfurb**

### CODE REVIEW

**Comment by RagnarArdal** [comment]
I'm pretty sure this code should go somewhere else, the top contender in permuta would be in the misc submodule. Let's talk about it when we next meet.

**Comment by RagnarArdal** [comment]
Move this module to the permuta.misc submodule for now and resolve the gitignore conflict (we have a new big gitignore, so your changes may be unnecessary). Then we can merge the pull request.

**Comment by alfurb** [comment]
Fixed the gitignore and moved the files but I still have some more testing to do. Don't merge yet, sawry

**Comment by alfurb** [comment]
I think I've finished now. Could @RagnarArdal or @christianbean take one more look and merge if ok?

**Pull request merged**
