### PR TITLE
Improve plotting

### PR DESCRIPTION
**Pull request by enadeau**
- [x] Improve the `_ascii_plot` method
- [x] Make the `ascii_plot` method acessible
- [x] Improve the `to_tikz` method
- [x] Fix the `plot` method

### CODE REVIEW

**Comment by christianbean** [comment]
I suggest the plot method return the ascii plot for version 2. In a future version we may add a new plot function.

**Comment by christianbean** [comment]
Should plot just be an alias for ascii_plot, until plot is implemented, therefore removing all mentions of matplotlib?

**Comment by enadeau** [comment]
I've clean the plot function. It now raises
```
NotImplementedError: Set `use_mpl=False` for an ascii plot or use `to_tikz` method
```
if use mpl is set to `True`

**Comment by enadeau** [comment]
> Should plot just be an alias for ascii_plot, until plot is implemented, therefore removing all mentions of matplotlib?

I tought thatk keeping it this way would allow to update the function without a major version changes in the future

**Comment by christianbean** [comment]
A future function may not use matplotlib. For example, the demo had a plot function using seaborn. The function should reflect this.

**Comment by enadeau** [comment]
Yeah that's true, I'll change it

**Comment by enadeau** [comment]
I've also remove the seaborn extra requirement in the setup.py

**Comment by christianbean** [comment]
This is ready to merge then!

**Pull request merged**
